apiVersion: v1
kind: Secret
metadata:
  name: ms2-crud-env
  namespace: codechallenge
type: Opaque
stringData:
  PORT: "3001"
  MONGO_URI: "mongodb://mongo:27017/profiledb"
  JWT_SECRET: "CODETSCSCALLENGEP!@xZZZ23"
  CORS_ORIGIN: "https://localhost:3001"
  NUMVERIFY_KEY: "72abb372ac845b678926b146b8069c35"
  INTERNAL_USER: "MS1POPULARUSER"
  INTERNAL_PASS: "MS1POPULARPASS!"
  VERIFICATION_EMAIL_FROM: "treisychenoa@gmail.com"
  VERIFICATION_EMAIL_PASS: "tklr lmzq hvcq ejeg"
  VERIFICATION_CODE_TTL_MINUTES: "10"
  HOSTSERVER: "smtp.gmail.com"
  API_KEY_SECRET: "MSCOMMUNPASSSECRET!@"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: ms1-getprofile-env
  namespace: codechallenge
type: Opaque
stringData:
  PORT: "3000"
  JWT_SECRET: "CODETSCSCALLENGEP!@xZZZ23"
  CORS_ORIGIN: "http://localhost:3000"
  INTERNAL_USER: "MS1POPULARUSER"
  INTERNAL_PASS: "MS1POPULARPASS!"
  BASE_URL_MS2: "http://ms2-crud:3001"
  API_KEY_SECRET: "MSCOMMUNPASSSECRET!@"